import React,{useEffect,useState}from'react';
import{api}from'./api.js';
import{ShieldCheck,AlertTriangle,RefreshCw}from'lucide-react';

export default function ComplianceStatus({token}){
  const[data,setData]=useState(null),[ruleData,setRuleData]=useState(null),[error,setError]=useState('');
  const load=()=>{setError('');Promise.all([api('/api/tests',{token}),api('/api/rules',{token})]).then(([tests,rules])=>{setData(tests);setRuleData(rules)}).catch(e=>setError(e.message))};
  useEffect(load,[token]);
  if(error)return <div className="failure"><AlertTriangle/><div><b>Unable to load compliance results.</b><span>{error}</span></div><button className="secondary" onClick={load}>Retry</button></div>;
  if(!data||!ruleData)return <div className="loading"><RefreshCw className="spin"/> Loading evaluations…</div>;
  const tests=Array.isArray(data)?data:[],sets=Array.isArray(ruleData?.active_rule_sets)?ruleData.active_rule_sets:[];
  const rows=tests.flatMap(t=>(Array.isArray(t?.results)?t.results:[]).map(r=>({...r,t})));
  const demo=sets.some(s=>s?.non_official);
  return <>
    <div className="page-heading"><div><div className="panel-kicker">RULE EVALUATION</div><h1>Compliance status</h1><p>Measured values, versioned rules and controlled evaluation outcomes.</p></div></div>
    <div className="rule-alert"><ShieldCheck/><div><b>{sets.length?'Active rule configurations':ruleData?.active_versions?.length?'Active rule configurations detected':'No active rule configuration'}</b><span>{sets.length?sets.map((s,i)=>`${s?.standard_name||'Standard'} ${s?.version||''} · ${Number(s?.rule_count)||0} rules · ${(Array.isArray(s?.accuracy_classes)?s.accuracy_classes:[]).join(', ')||'classes not reported'}`).join(' | '):ruleData?.active_versions?.length?ruleData.active_versions.join(', ')+' (rule-set detail is unavailable from this backend version).':'Evaluations remain NOT EVALUATED until an administrator configures applicable rules.'}{demo?' The SIH demo profile is synthetic and non-official; it is not legal guidance.':''}</span></div></div>
    {sets.length>0&&<div className="card table-card compliance-table"><div className="table-wrap"><table><thead><tr><th>CONFIGURATION</th><th>STATUS</th><th>TEST COVERAGE</th><th>CLASSES</th></tr></thead><tbody>{sets.map((s,i)=><tr key={s?.id||`${s?.standard_name||'set'}-${s?.version||i}`}><td><b>{s?.standard_name||'Standard'}</b><small>{s?.version||'Version unavailable'}</small></td><td><span className={'coverage-state '+(s?.non_official?'missing':'configured')}>{s?.status||'ACTIVE CONFIGURED'}</span></td><td>{(Array.isArray(s?.test_types)?s.test_types:[]).join(', ')||'Not reported'}</td><td>{(Array.isArray(s?.accuracy_classes)?s.accuracy_classes:[]).join(', ')||'Not reported'}</td></tr>)}</tbody></table></div></div>}
    {rows.length?<div className="card table-card compliance-table"><div className="table-wrap"><table><thead><tr><th>TEST SESSION</th><th>TEST</th><th>RULE</th><th>CALCULATED VALUE</th><th>PERMITTED LIMIT</th><th>STATUS</th><th>RULE VERSION</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.t.id}-${r.id}`}><td>TS-{String(r.t.id).padStart(4,'0')}<small>{r.t.model} · {r.t.instrument}</small></td><td>{r.test_type}</td><td><b>{r.rule_code||'MISSING_RULE'}</b><small>{r.rule_description}</small></td><td>{r.calculated_value??'Not available'} {r.calculated_unit}</td><td>{r.limit_value??(r.status==='NOT_EVALUATED'?'Not configured':'See comparison details')} {r.limit_unit}</td><td><span className={'coverage-state '+(r.status==='PASS'?'configured':r.status==='FAIL'?'failed':'missing')}>{r.status==='NOT_EVALUATED'?'NOT EVALUATED':r.status}</span></td><td>{r.standard_name} · {r.standard_version}<details><summary>Compared rule limits</summary><p>{r.details}</p></details></td></tr>)}</tbody></table></div></div>:<div className="card"><div className="empty-inline"><div><ShieldCheck/></div><b>No compliance evaluations yet</b><span>Run an evaluation from a test session. Raw values can be inspected before rule configuration is available.</span></div></div>}
  </>;
}
