import React,{useEffect,useState}from'react';
import{AlertTriangle,ArrowDownToLine,Eye,FileText,RefreshCw,Search,X}from'lucide-react';
import{api}from'./api.js';
export default function ReportRepository({token}){
 const[rows,setRows]=useState(null),[q,setQ]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[detail,setDetail]=useState(null);
 const load=()=>{setError('');api(`/api/reports?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`,{token}).then(setRows).catch(e=>setError(e.message))};
 useEffect(()=>{load()},[token,q,status]);
 const download=async(id,fmt)=>{try{const blob=await api(`/api/reports/${id}/${fmt}`,{token});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`report-${id}.${fmt}`;a.click();URL.revokeObjectURL(a.href)}catch(e){setError(e.message)}};
 const view=async id=>{try{setDetail(await api(`/api/reports/${id}`,{token}))}catch(e){setError(e.message)}};
 if(error)return <div className="failure"><AlertTriangle/><div><b>Unable to load the report repository.</b><span>{error}</span></div><button className="secondary" onClick={load}>Retry</button></div>;
 if(!rows)return <div className="loading"><RefreshCw className="spin"/> Loading reports…</div>;
 return <><div className="page-heading"><div><div className="panel-kicker">DOCUMENT REPOSITORY</div><h1>Reports & repository</h1><p>Generated laboratory reports, review states and downloadable source documents.</p></div></div>
  <div className="toolbar card"><div className="search"><Search size={17}/><input placeholder="Search report ID, serial number or model" value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label="Filter reports" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses and results</option>{['PENDING','PASS','FAIL','APPROVED','REJECTED'].map(x=><option key={x}>{x}</option>)}</select><span className="count">{rows.length} reports</span></div>
  <div className="card table-card"><div className="table-wrap"><table><thead><tr><th>REPORT ID</th><th>INSTRUMENT</th><th>TEST DATE</th><th>OPERATOR</th><th>RESULT</th><th>REVIEW</th><th>CREATED</th><th>ACTIONS</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.report_number}</td><td><b>{r.model}</b><small>{r.serial_number}</small></td><td>{r.test_date}</td><td>{r.operator}</td><td><span className={'status '+(r.overall_status==='PASS'?'good':r.overall_status==='FAIL'?'bad':'neutral')}><i/>{r.overall_status}</span></td><td><span className="status pending"><i/>{r.status.replaceAll('_',' ')}</span></td><td>{new Date(r.created_at).toLocaleDateString()}</td><td><button className="link-btn" onClick={()=>view(r.id)}><Eye size={14}/> View</button><button className="link-btn" onClick={()=>download(r.id,'pdf')}><ArrowDownToLine size={14}/> PDF</button><button className="link-btn" onClick={()=>download(r.id,'docx')}><ArrowDownToLine size={14}/> DOCX</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty-inline"><div><FileText/></div><b>No reports match this view</b><span>Generate a test report after running a compliance evaluation.</span></div>}</div>
  {detail&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><div className="modal wide"><header><div><div className="panel-kicker">REPORT DETAIL</div><h2>{detail.report_number}</h2></div><button className="icon-button" onClick={()=>setDetail(null)}><X/></button></header><div className="detail-grid"><div><small>Instrument</small><b>{detail.instrument.manufacturer} {detail.instrument.model}</b></div><div><small>Serial</small><b>{detail.instrument.serial_number}</b></div><div><small>Test date</small><b>{detail.test_date}</b></div><div><small>Review status</small><b>{detail.status}</b></div><div><small>Overall engine result</small><b>{detail.overall_status}</b></div></div><h3 className="subhead">Evaluation</h3><div className="table-wrap"><table><thead><tr><th>TEST</th><th>VALUE</th><th>LIMIT</th><th>RESULT</th><th>DETAILS</th></tr></thead><tbody>{detail.results.map(r=><tr key={r.test_type}><td>{r.test_type}</td><td>{r.calculated_value??'—'}</td><td>{r.limit_value??'Not configured'}</td><td>{r.status}</td><td>{r.details}</td></tr>)}</tbody></table></div><div className="modal-actions"><button className="secondary" onClick={()=>download(detail.id,'pdf')}><ArrowDownToLine size={15}/> Download PDF</button><button className="secondary" onClick={()=>download(detail.id,'docx')}><ArrowDownToLine size={15}/> Download DOCX</button></div></div></div>}
 </>;
}
