import React,{useEffect,useState}from'react';
import{Activity,AlertTriangle,ArrowDownToLine,Beaker,Check,ClipboardList,FileText,Plus,RefreshCw,Scale,Search,ShieldCheck,X}from'lucide-react';
import{api}from'./api.js';
import TestEvidence from'./TestEvidence.jsx';

const emptyRow=()=>({test_type:'WEIGHING',test_point:'',applied_load:'',indicated_value:''});
const passSample=[
 {test_type:'WEIGHING',test_point:'0.2 kg point',applied_load:0.2,indicated_value:0.2},
 {test_type:'WEIGHING',test_point:'5 kg point',applied_load:5,indicated_value:5.01},
 {test_type:'WEIGHING',test_point:'13 kg point',applied_load:13,indicated_value:13.01},
 {test_type:'WEIGHING',test_point:'26 kg point',applied_load:26,indicated_value:26.01},
 ...[13,13.01,12.99,13,13].map((v,i)=>({test_type:'REPEATABILITY',test_point:`Repeat ${i+1}`,applied_load:13,indicated_value:v})),
 ...[13,13.01,12.99,13,13.01].map((v,i)=>({test_type:'ECCENTRICITY',test_point:['Center','Front-left','Front-right','Rear-left','Rear-right'][i],applied_load:13,indicated_value:v})),
 {test_type:'TARE',test_point:'Tare check',applied_load:2,indicated_value:2.005},
];

export default function TestSessions({token,user,notify,reviewOnly=false}){
 const[tests,setTests]=useState(null),[instruments,setInstruments]=useState([]),[error,setError]=useState(''),[q,setQ]=useState(''),[create,setCreate]=useState(false),[active,setActive]=useState(null),[rows,setRows]=useState([emptyRow()]),[busy,setBusy]=useState(false),[report,setReport]=useState(null);
 const load=()=>{setError('');Promise.all([api('/api/tests',{token}),api('/api/instruments',{token})]).then(([a,b])=>{setTests(a);setInstruments(b)}).catch(e=>setError(e.message))};
 useEffect(()=>{load()},[token]);
 const openSession=t=>{setActive(t);setRows(t.observations.length?t.observations.map(o=>({...o,applied_load:String(o.applied_load),indicated_value:String(o.indicated_value)})):[emptyRow()]);setReport(null)};
 const createSession=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.instrument_id=Number(f.instrument_id);for(const k of ['temperature','humidity','pressure'])f[k]=f[k]?Number(f[k]):null;setBusy(true);try{const t=await api('/api/tests',{token,method:'POST',body:JSON.stringify(f)});setCreate(false);openSession(t);notify('Test session created; the signed-in technician is recorded as operator.');load()}catch(e){notify(e.message)}finally{setBusy(false)}};
 const save=async()=>{const observations=rows.map(o=>({...o,applied_load:Number(o.applied_load),indicated_value:Number(o.indicated_value)}));if(observations.some(o=>!Number.isFinite(o.applied_load)||!Number.isFinite(o.indicated_value)))return notify('Enter a valid applied load and indication for every row.');setBusy(true);try{const t=await api(`/api/tests/${active.id}/observations`,{token,method:active.observations.length?'PUT':'POST',body:JSON.stringify({observations})});openSession(t);notify('Observation set saved; prior results were invalidated.')}catch(e){notify(e.message)}finally{setBusy(false)}};
 const calculate=async()=>{if(!rows.length)return notify('Add at least one measurement before running compliance.');const observations=rows.map(o=>({...o,applied_load:Number(o.applied_load),indicated_value:Number(o.indicated_value)}));if(observations.some(o=>!Number.isFinite(o.applied_load)||!Number.isFinite(o.indicated_value)))return notify('Enter a valid applied load and indication for every row.');setBusy(true);try{await api(`/api/tests/${active.id}/observations`,{token,method:active.observations.length?'PUT':'POST',body:JSON.stringify({observations})});await api(`/api/tests/${active.id}/run-compliance`,{token,method:'POST'});const t=await api(`/api/tests/${active.id}`,{token});openSession(t);load();notify(`Evaluation complete: ${t.overall_status}.`)}catch(e){notify(e.message)}finally{setBusy(false)}};
 const submit=async()=>{setBusy(true);try{const t=await api(`/api/tests/${active.id}/submit`,{token,method:'POST'});openSession(t);load();notify('Passing session sent to an approving officer.')}catch(e){notify(e.message)}finally{setBusy(false)}};
 const review=async decision=>{let reason='';if(decision==='REJECT'){reason=prompt('Enter the review rejection reason:')||'';if(!reason.trim())return}setBusy(true);try{const t=await api(`/api/tests/${active.id}/review`,{token,method:'POST',body:JSON.stringify({decision,reason})});openSession(t);load();notify(`Review recorded: ${t.status}.`)}catch(e){notify(e.message)}finally{setBusy(false)}};
 const generate=async()=>{setBusy(true);try{const r=await api(`/api/reports/from-test/${active.id}`,{token,method:'POST'});setReport(r);load();notify(`Report ${r.report_number} generated as PDF and DOCX.`)}catch(e){notify(e.message)}finally{setBusy(false)}};
 const download=async(id,fmt)=>{try{const blob=await api(`/api/reports/${id}/${fmt}`,{token});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`report-${id}.${fmt}`;a.click();URL.revokeObjectURL(a.href)}catch(e){notify(e.message)}};
 if(error)return <div className="failure"><AlertTriangle/><div><b>Unable to load test workflow.</b><span>{error}</span></div><button className="secondary" onClick={load}>Retry</button></div>;
 if(!tests)return <div className="loading"><RefreshCw className="spin"/> Loading test sessions…</div>;
 const canEdit=active&&['DRAFT','IN_PROGRESS','COMPLETED','REJECTED'].includes(active.status)&&['ADMIN','LAB_TECHNICIAN'].includes(user.role);
 const filtered=tests.filter(t=>(!reviewOnly||t.status==='UNDER_REVIEW')&&`${t.id} ${t.model} ${t.instrument} ${t.operator} ${t.status}`.toLowerCase().includes(q.toLowerCase()));
 return <>
  <div className="page-heading"><div><div className="panel-kicker">{reviewOnly?'OFFICER DECISION WORKFLOW':'TRACEABLE LABORATORY WORKFLOW'}</div><h1>{reviewOnly?'Review queue':'Test sessions'}</h1><p>{reviewOnly?'Inspect submitted results, then approve or reject each session.':'Record physical measurements, run configured calculations, and route passing results to officer review.'}</p></div>{!reviewOnly&&['ADMIN','LAB_TECHNICIAN'].includes(user.role)&&<button className="primary" onClick={()=>setCreate(true)}><Plus size={17}/> Create test session</button>}</div>
  <div className="toolbar card"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search session, instrument, operator, status"/></div><span className="count">{tests.length} sessions</span></div>
  <div className="card table-card"><div className="table-wrap"><table><thead><tr><th>SESSION</th><th>INSTRUMENT / SERIAL</th><th>DATE</th><th>OPERATOR</th><th>RESULT</th><th>WORKFLOW</th><th>ACTION</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td className="mono">TS-{String(t.id).padStart(4,'0')}</td><td><b>{t.model}</b><small>{t.instrument}</small></td><td>{t.test_date}</td><td>{t.operator}</td><td><span className={'status '+(t.overall_status==='PASS'?'good':t.overall_status==='FAIL'?'bad':'neutral')}><i/>{t.overall_status}</span></td><td><span className="status pending"><i/>{t.status.replaceAll('_',' ')}</span></td><td><button className="link-btn" onClick={()=>openSession(t)}>{reviewOnly?'Review submission':'Open workbench'}</button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="empty-inline"><div><ClipboardList/></div><b>{reviewOnly?'No sessions awaiting review':tests.length?'No matching test sessions':'No test sessions yet'}</b><span>{reviewOnly?'Passing sessions submitted for officer review will appear here.':'Register an instrument, then create the first laboratory test session.'}</span></div>}</div>
  {create&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setCreate(false)}><div className="modal"><header><h2>Create test session</h2><button className="icon-button" onClick={()=>setCreate(false)}><X/></button></header>{instruments.length?<form className="form-grid" onSubmit={createSession}><label className="full">Instrument<select name="instrument_id" required defaultValue=""><option value="" disabled>Select a registered instrument</option>{instruments.map(i=><option key={i.id} value={i.id}>{i.manufacturer} {i.model} · {i.serial_number} · Class {i.accuracy_class}</option>)}</select></label><label>Test date<input name="test_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Operator<input value={`${user.name} (signed-in user)`} disabled/><small>Recorded by the backend from your authenticated account.</small></label><label>Laboratory<input name="laboratory" placeholder="Laboratory name"/></label><label>Temperature (°C)<input name="temperature" type="number" step="any"/></label><label>Relative humidity (%RH)<input name="humidity" type="number" step="any"/></label><label>Pressure (hPa)<input name="pressure" type="number" step="any"/></label><label className="full">Remarks<textarea name="remarks"/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setCreate(false)}>Cancel</button><button disabled={busy} className="primary">Create session</button></div></form>:<div className="empty-inline"><div><Scale/></div><b>Register an instrument first</b><span>Test sessions must point to an actual instrument record.</span><button className="secondary" onClick={()=>setCreate(false)}>Close</button></div>}</div></div>}
  {active&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setActive(null)}><div className="modal wide workbench"><header><div><div className="panel-kicker">SESSION TS-{String(active.id).padStart(4,'0')}</div><h2>Test execution workbench</h2></div><button className="icon-button" onClick={()=>setActive(null)}><X/></button></header>
   <div className="session-meta"><span className="status pending"><i/>{active.status.replaceAll('_',' ')}</span><span>{active.model} · {active.instrument}</span><span>{active.test_date} · Operator: {active.operator}</span></div>
   <div className="instrument-technical"><b>{active.model}</b><span>Serial {active.instrument}</span><span>Session {active.laboratory||'Laboratory not specified'}</span><span>{active.temperature??'—'} °C</span><span>{active.humidity??'—'} %RH</span><span>{active.pressure??'—'} hPa</span></div>
   <TestEvidence testId={active.id} token={token} notify={notify} canUpload={['ADMIN','LAB_TECHNICIAN'].includes(user.role)}/>
   <div className="section-head"><div><h3>{reviewOnly?'Submitted measurement record':'Measurement record'}</h3><p>{reviewOnly?'Read-only observations submitted by the technician.':'Record actual readings from the physical test; error is calculated as indication minus applied load.'}</p></div>{!reviewOnly&&<button className="secondary small" disabled={!canEdit} onClick={()=>{setRows(passSample.map(o=>({...o,applied_load:String(o.applied_load),indicated_value:String(o.indicated_value)})));notify('Sample readings loaded. SIMULATED DATA — replace with physical measurements before real use.')}}>Load simulated PASS sample</button>}</div>
   {!reviewOnly&&<div className="demo-warning"><AlertTriangle size={17}/><span>Sample readings are simulated solely for demonstration. They are not measurements from a physical instrument.</span></div>}
   <div className="workbench-rows"><div className="workbench-row workbench-head"><span>TEST MODULE</span><span>TEST POINT</span><span>APPLIED LOAD</span><span>INDICATION</span><span>ERROR (AUTO)</span><span/></div>{rows.map((o,i)=><div className="workbench-row" key={i}><select disabled={!canEdit} aria-label="Test module" value={o.test_type} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,test_type:e.target.value}:x))}>{['WEIGHING','REPEATABILITY','ECCENTRICITY','TARE'].map(x=><option key={x}>{x}</option>)}</select><input disabled={!canEdit} aria-label="Test point" value={o.test_point} placeholder="Point / position" onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,test_point:e.target.value}:x))}/><input disabled={!canEdit} aria-label="Applied load" type="number" step="any" value={o.applied_load} placeholder="kg" onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,applied_load:e.target.value}:x))}/><input disabled={!canEdit} aria-label="Indication" type="number" step="any" value={o.indicated_value} placeholder="kg" onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,indicated_value:e.target.value}:x))}/><b>{o.applied_load!==''&&o.indicated_value!==''?(Number(o.indicated_value)-Number(o.applied_load)).toFixed(4):'—'}</b><button className="icon-button" aria-label="Remove observation" disabled={!canEdit} onClick={()=>setRows(rows.filter((_,j)=>j!==i))}><X size={15}/></button></div>)}</div>
   {!reviewOnly&&<div className="modal-actions"><button className="secondary" disabled={!canEdit} onClick={()=>setRows([...rows,emptyRow()])}><Plus size={15}/> Add observation</button><button className="secondary" disabled={busy||!canEdit||!rows.length} onClick={save}>Save observations</button><button className="primary" disabled={busy||!canEdit||!rows.length} onClick={calculate}><Beaker size={16}/> {busy?'Evaluating…':'Run compliance'}</button></div>}
   {!!active.results.length&&<><div className="compliance-summary"><div><span className="panel-kicker">BACKEND EVALUATION</span><h3>OIML R-76 test summary</h3></div><span className={'status '+(active.overall_status==='PASS'?'good':active.overall_status==='FAIL'?'bad':'neutral')}><i/>{active.overall_status}</span></div><div className="result-grid">{active.results.map(r=><article key={r.id} className="card result-card"><div className="result-top"><div className="metric-icon tint4"><Activity size={17}/></div><span className={'status '+(r.status==='PASS'?'good':r.status==='FAIL'?'bad':'neutral')}><i/>{r.status}</span></div><h3>{r.test_type}</h3><div className="calc-values"><div><small>CALCULATED</small><b>{r.calculated_value??'—'} {r.calculated_unit}</b></div><div><small>LIMIT</small><b>{r.limit_value??'Not configured'} {r.limit_unit}</b></div></div><p>{r.details}</p><small>{r.rule_code} · {r.standard_version}</small></article>)}</div>
    <div className="rule-alert"><ShieldCheck/><div><b>Decision source: backend rule engine</b><span>All five tests must have active applicable rules and sufficient observations for PASS. A measured FAIL is reported immediately. A synthetic demonstration profile is not official OIML guidance.</span></div></div>
    <div className="modal-actions workflow-actions">{active.overall_status==='PASS'&&['ADMIN','LAB_TECHNICIAN'].includes(user.role)&&active.status!=='UNDER_REVIEW'&&active.status!=='APPROVED'&&<button className="primary" disabled={busy} onClick={submit}>Submit to officer review</button>}{active.status==='UNDER_REVIEW'&&['ADMIN','APPROVING_OFFICER'].includes(user.role)&&<><button className="primary" disabled={busy} onClick={()=>review('APPROVE')}>Approve</button><button className="secondary" disabled={busy} onClick={()=>review('REJECT')}>Reject with reason</button></>}{['COMPLETED','UNDER_REVIEW','APPROVED','REJECTED'].includes(active.status)&&<button className="primary" disabled={busy} onClick={generate}><FileText size={16}/> Generate Test Report</button>}</div>
    {report&&<div className="report-downloads"><b>Generated report · {report.report_number}</b><button className="link-btn" onClick={()=>download(report.id,'pdf')}><ArrowDownToLine size={15}/> Download PDF</button><button className="link-btn" onClick={()=>download(report.id,'docx')}><ArrowDownToLine size={15}/> Download DOCX</button></div>}
   </>}
  </div></div>}
 </>;
}
